version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mcosantander/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mlbbradesco/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mlbvotorantim/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mlcscotiabank/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gradle"
    directory: "/mlmbbva/"
    schedule:
      interval: "daily"
